export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILED = "GET_CARDS_FAILED";
export const REMOVE_A_CARD = "REMOVE_A_CARD";
